---
title: "education_race_eda"
format: pdf
---

```{r}
library(tidyverse)
library(arrow)
library(ggthemes)

data <- read_parquet("../data/clean_data.parquet")
```

```{r}
glimpse(data[1:27])
```

```{r}
education_eda_30 <- data %>% 
  filter(age >= 30,
         esr != "Not in Labor Force"
         ) %>% 
  select(age,
         race,
         race_simp,
         gross_rent,
         income_personal,
         education,
         health_insurance,
         snap_benefits,
         puma)

glimpse(education_eda_30)
```

```{r}
education_eda_30 %>%
  filter(income_personal <= 500000) %>% 
  ggplot() +
    geom_boxplot(aes(x = income_personal / 1000,
                     y = reorder(education, income_personal)),
                 outlier.shape = NA) + 
  theme_few() +
  ylab("") +
  xlab("Income (thousands)") +
  labs(title = "Higher Education Level Is Associated with Higher Income",
       caption = "Source: ACS PUMS 2024 for LA County") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
education_eda_30 %>% 
  ggplot() +
    geom_bar(aes(y = reorder(education, income_personal, mean),
                 fill = race_simp),
             position = "fill") +
  scale_fill_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00")) +
  theme_few() +
  xlab("")+
  ylab("") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(fill = "",
       title = "Race Is Disproportionately Spread Across Education Levels",
       caption = "Source: ACS PUMS 2024 for LA County")
```

```{r}
education_eda_30 %>% 
  mutate(income_brackets = case_when(income_personal <= 15000 ~ "0-15k",
                                     income_personal <= 30000 ~ "15k-30k",
                                     income_personal <= 60000 ~ "30k-60k",
                                     income_personal <= 90000 ~ "60k-90k",
                                     income_personal <= 120000 ~ "90k-120k",
                                     income_personal <= 150000 ~ "120k-150k",
                                     income_personal > 150000 ~ "150k+")) %>% 
  select(race_simp, income_brackets, income_personal) %>%
  ggplot() +
    geom_bar(aes(y = reorder(income_brackets,income_personal),
                 fill = race_simp),
             position = "fill") +
    scale_fill_manual(values = c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00")) +
    theme_few() +
    theme(axis.text.x = element_blank(),
         axis.ticks.x = element_blank()) +
    labs(fill = "",
         title = "Race Is Disproportionately Spread Across Income Brackets",
        caption = "Source: ACS PUMS 2024 for LA County") +
    xlab("")+
    ylab("")
```

